### ISSUE TITLE
Gregtech

### ISSUE THREAD

**Issue by mightydanp** [mightydanp/RodRubbersPublicPack#2]
@GregoriusT
I want you to take a look at this.
https://docs.google.com/document/d/1fop3gF0zmepGDBtrYOfaSij5AMhhhBWzcgeOYTb4r0A/edit?ts=57eb348c#

**Comment by mightydanp** [comment]
http://ipic.su/img/img7/fs/kiss_240kb.1488993123.png

**Comment by GregoriusT** [comment]
Sounds like a good Modular Machine System. Can't say much else about it. ;)

I once thought of a similar yet slightly different Microblock Block
alike System, but decided to not add it in MC, due to how bad MC is in
those regards.

**Comment by mightydanp** [comment]
True in 1.12 they have redone and tweaked some of the rendering to fix most of the tile entity lag. Would u think about giving it a shot for 1.12

**Comment by GregoriusT** [comment]
Nope, I'm stopping MC entirely after I am done with GT6 (what might
still take one or two years), and after that I will make my own Block
Game that is not as crappy as MC. I need a stable Platform, and MC
cannot deliver on that at all.

**Comment by draknyte1** [comment]
@Dragon2488 did this work above for 1.10 and tossed out the idea due to how shit the rendering system now is.

**Comment by mightydanp** [comment]
@GregoriusT eloraam  is making her own game for redpower.

**Comment by draknyte1** [comment]
Eventually all the big mod devs make their own game. Azanor? (TC Dev) wants to do the same and it's why he won't let anyone take over further TC development.

**Comment by mightydanp** [comment]
true but someone will always rip it off somehow

**Comment by GregoriusT** [comment]
Didn't Azanor stop, because his real life was becoming too busy to do anything?

And I know Eloraam does her own Game, I looked at her Twitter
regularily until Twitter changed something to make it impossible to
look at all Tweets and Answers without having an Account...

Well my Game would be different from the Redpower Game, still
Blockbased but a lot different, especially Graphics wise.

**Comment by mightydanp** [comment]
What so u have as an idea right now foe ur game

**Comment by GregoriusT** [comment]
Yeah but I'm not in the mood to talk atm due to irl headache. ;P
